var defaultProps = {
    accessibility: true,
    adaptiveHeight: false,
    // appendArrows: $(element),
    // appendDots: $(element),
    arrows: true,
    asNavFor: null,
    // prevArrow: '<button type="button" data-role="none" class="slick-prev">Previous</button>',
    // nextArrow: '<button type="button" data-role="none" class="slick-next">Next</button>',
    autoplay: false,
    autoplaySpeed: 3000,
    centerMode: false,
    centerPadding: '50px',
    cssEase: 'ease',
    // customPaging: function(slider, i) {
    //     return '<button type="button" data-role="none">' + (i + 1) + '</button>';
    // },
    dots: false,
    dotsClass: 'slick-dots',
    draggable: true,
    easing: 'linear',
    fade: false,
    focusOnSelect: false,
    infinite: true,
    initialSlide: 0,
    lazyLoad: 'ondemand',
    onBeforeChange: null,
    onAfterChange: null,
    onInit: null,
    onReInit: null,
    onSetPosition: null,
    pauseOnHover: true,
    pauseOnDotsHover: false,
    respondTo: 'window',
    responsive: null,
    rtl: false,
    slide: 'div',
    slidesToShow: 1,
    slidesToScroll: 1,
    speed: 500,
    swipe: true,
    swipeToSlide: false,
    touchMove: true,
    touchThreshold: 5,
    // useCSS: true,
    variableWidth: false,
    vertical: false,
    // waitForAnimate: true
};

module.exports = defaultProps;